language: julia

sudo: required

os:
  - linux
  - osx

addons:
  apt:
    packages:
    - libmpfi-dev

before_install:
  - if [ `uname` = "Darwin" ]; then brew install mpfi; fi

julia:
  - 0.5
  - 0.6
  - nightly

# matrix:
#   allow_failures:
#     - julia: 0.6
#     - julia: nightly

notifications:
  email: false

after_success:
- julia -e 'cd(Pkg.dir("MPFI")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
